# The five ordinary policies that make up each LEKMOD policy branch. The
# game log never fires a distinct "finisher policy adopted" event under
# any id, so a branch's completion is read off all five of these instead.
# Shared between KeyMomentDetector and OpeningStrategy so neither can
# drift out of sync with the other on which five policies close which
# branch.
#
# LEKMOD keeps the underlying policy IDs from vanilla Civ5 BNW even where
# it renames the displayed policy (e.g. POLICY_MERCHANT_NAVY is shown
# in-game as "Colonialism" under Exploration), so these are internal
# constant names, not display names.
module LekmodBranchPolicies
  BRANCHES = {
    "POLICY_BRANCH_TRADITION" => %w[POLICY_LEGALISM POLICY_LANDED_ELITE POLICY_MONARCHY POLICY_OLIGARCHY POLICY_ARISTOCRACY],
    "POLICY_BRANCH_LIBERTY" => %w[POLICY_REPUBLIC POLICY_COLLECTIVE_RULE POLICY_CITIZENSHIP POLICY_REPRESENTATION POLICY_MERITOCRACY],
    "POLICY_BRANCH_HONOR" => %w[POLICY_WARRIOR_CODE POLICY_PROFESSIONAL_ARMY POLICY_MILITARY_CASTE POLICY_DISCIPLINE POLICY_MILITARY_TRADITION],
    "POLICY_BRANCH_PIETY" => %w[POLICY_ORGANIZED_RELIGION POLICY_REFORMATION POLICY_MANDATE_OF_HEAVEN POLICY_FREE_RELIGION POLICY_THEOCRACY],
    "POLICY_BRANCH_EXPLORATION" => %w[POLICY_NAVAL_TRADITION POLICY_MARITIME_INFRASTRUCTURE POLICY_MERCHANT_NAVY POLICY_NAVIGATION_SCHOOL POLICY_TREASURE_FLEETS],
    "POLICY_BRANCH_RATIONALISM" => %w[POLICY_SOVEREIGNTY POLICY_FREE_THOUGHT POLICY_HUMANISM POLICY_SCIENTIFIC_REVOLUTION POLICY_SECULARISM],
    "POLICY_BRANCH_PATRONAGE" => %w[POLICY_MERCHANT_CONFEDERACY POLICY_SCHOLASTICISM POLICY_CULTURAL_DIPLOMACY POLICY_PHILANTHROPY POLICY_CONSULATES],
    "POLICY_BRANCH_COMMERCE" => %w[POLICY_SILK_ROAD POLICY_MERCENARY_ARMY POLICY_ENTREPRENEURSHIP POLICY_MERCANTILISM POLICY_PROTECTIONISM],
    "POLICY_BRANCH_AESTHETICS" => %w[POLICY_CULTURAL_CENTERS POLICY_CULTURAL_EXCHANGE POLICY_ARTISTIC_GENIUS POLICY_FLOURISHING_OF_THE_ARTS POLICY_FINE_ARTS]
  }.freeze
end
